version: '2'
services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # 添加映射初始化脚本的volumes
    networks:
      - app_net
    command: --init-file /docker-entrypoint-initdb.d/init.sql
    container_name: go-gin-vul-mysql

  redis:
    image: redis:latest
    restart: always
    volumes:
      - redis_data:/data
    networks:
      - app_net
    container_name: go-gin-vul-redis

  app:
    image: godzzzz/go-gin-vul:latest
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis
    environment:
      DATABASE_URL: "root:my-secret-pw@tcp(mysql:3306)/blog?charset=utf8&parseTime=True&loc=Local"
    networks:
      - app_net
    container_name: go-gin-vul-app

volumes:
  mysql_data:
  redis_data:

networks:
  app_net:
